// Generated by CoffeeScript 1.7.1

/*
Flowqueues - Queue based programming for node.js
(c) Copyright 2014 Applidget SAS
Released under the MIT License
 */

(function() {
  var colorizeInt;

  colorizeInt = function(id) {
    var color, colors, idx, reset;
    reset = "\u001b[0m";
    colors = ["\u001b[31m", "\u001b[32m", "\u001b[33m", "\u001b[34m", "\u001b[35m", "\u001b[36m", "\u001b[37m"];
    idx = id % colors.length;
    color = colors[idx];
    return color + id + reset;
  };

  exports.colorizeInt = colorizeInt;

}).call(this);
