// Generated by CoffeeScript 1.7.1

/*
Flowqueues - Queue based programming for node.js
(c) Copyright 2014 Applidget SAS
Released under the MIT License
 */

(function() {
  var Config;

  Config = (function() {
    function Config(dataSource) {
      var interval, queues_config_var;
      this.dataSource = dataSource;
      this.jobDescriptions = {};
      interval = process.env["INTERVAL"];
      if (interval != null) {
        this.timeoutInterval = parseInt(interval);
      } else {
        this.timeoutInterval = 5000;
      }
      queues_config_var = process.env["QUEUES"];
      if (queues_config_var != null) {
        this.queues = queues_config_var.split(",");
      } else {
        this.queues = ["critical", "main", "low"];
      }
    }

    Config.prototype.jobsDir = function() {
      return this.overridenJobDir || process.cwd();
    };

    Config.prototype.addJobDescription = function(jobDesc) {
      return this.jobDescriptions[jobDesc.name] = jobDesc;
    };

    return Config;

  })();

  exports.Config = Config;

}).call(this);
