// Generated by CoffeeScript 1.7.1

/*
Flowqueues - Queue based programming for node.js
(c) Copyright 2014 Applidget SAS
Released under the MIT License
 */

(function() {
  var clone, decode, encode, util, verbose, vverbose;

  util = require("util");

  encode = function(hash) {
    return JSON.stringify(hash);
  };

  decode = function(json) {
    var res;
    res = null;
    try {
      res = JSON.parse(json);
    } catch (_error) {
      log("PARSING ERROR: " + (util.inspect(util.inspect(json))));
    }
    return res;
  };

  clone = function(hash) {
    return decode(encode(hash));
  };

  verbose = function() {
    return vverbose() || process.env.VERBOSE === "true";
  };

  vverbose = function() {
    return process.env.VVERBOSE === "true";
  };

  exports.encode = encode;

  exports.decode = decode;

  exports.verbose = verbose;

  exports.vverbose = vverbose;

  exports.clone = clone;

}).call(this);
