// Generated by CoffeeScript 1.7.1

/*
Flowqueues - Queue based programming for node.js
(c) Copyright 2014 Applidget SAS
Released under the MIT License
 */

(function() {
  var JobDescription;

  JobDescription = (function() {
    function JobDescription(name) {
      this.name = name;
      this.taskDescriptions = {};
      this.taskNames = [];
      this.firstTaskName = null;
    }

    JobDescription.prototype.addTaskDescription = function(taskDesc) {
      this.taskDescriptions[taskDesc.name] = taskDesc;
      return this.taskNames.push(taskDesc.name);
    };

    JobDescription.prototype.setFirstTaskName = function(fistTaskName) {
      return this.firstTaskName = fistTaskName;
    };

    return JobDescription;

  })();

  exports.JobDescription = JobDescription;

}).call(this);
