// Generated by CoffeeScript 1.7.1

/*
Flowqueues - Queue based programming for node.js
(c) Copyright 2014 Applidget SAS
Released under the MIT License
 */

(function() {
  var TaskDescription;

  TaskDescription = (function() {
    function TaskDescription(name, nextDictionary, concurrency, timeout) {
      this.name = name;
      this.nextDictionary = nextDictionary != null ? nextDictionary : {};
      this.concurrency = concurrency != null ? concurrency : 1;
      this.timeout = timeout != null ? timeout : null;
      ({});
    }

    TaskDescription.prototype.setNextTaskNameForKey = function(key, otherTaskName) {
      return this.nextDictionary[key] = otherTaskName;
    };

    TaskDescription.prototype.getNextTaskNameForKey = function(key) {
      return this.nextDictionary[key];
    };

    return TaskDescription;

  })();

  exports.TaskDescription = TaskDescription;

}).call(this);
